-- 코드를 입력하세요
SELECT rf.REST_ID, rf.REST_NAME, rf.FOOD_TYPE, rf.FAVORITES, rf.ADDRESS, ROUND(AVG(rr.REVIEW_SCORE), 2) as SCORE
FROM REST_INFO rf
JOIN REST_REVIEW rr ON rf.REST_ID = rr.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY rf.REST_ID, rf.REST_NAME, rf.FOOD_TYPE, rf.FAVORITES, rf.ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC