-- 코드를 작성해주세요
WITH RECURSIVE CTE as (
    SELECT 
        ID, 
        PARENT_ID,
        1 as 'GENERATION'
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL

    SELECT 
        ed.ID,
        ed.PARENT_ID,
        (CTE.GENERATION + 1) as 'GENERATION'
    FROM ECOLI_DATA ed
    JOIN CTE ON ed.PARENT_ID = CTE.ID
)

SELECT COUNT(*) as 'COUNT', CTE.GENERATION
FROM CTE
LEFT JOIN ECOLI_DATA ed ON CTE.ID = ed.PARENT_ID
WHERE ed.ID IS NULL
GROUP BY CTE.GENERATION
ORDER BY CTE.GENERATION
