-- 코드를 입력하세요
SELECT MONTH(START_DATE) as 'MONTH', CAR_ID, COUNT(CAR_ID) as 'RECORDS'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c
WHERE c.START_DATE >= '2022-08-01'
    AND c.START_DATE < '2022-11-01'
    AND CAR_ID in (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY cc
        WHERE cc.START_DATE >= '2022-08-01'
            AND cc.START_DATE < '2022-11-01'
        GROUP BY CAR_ID
        HAVING COUNT(*) >= 5
    )
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH(START_DATE), CAR_ID DESC
