-- 코드를 작성해주세요
SELECT 
    YEAR(a.DIFFERENTIATION_DATE) AS 'YEAR',
    (m.SIZE - a.SIZE_OF_COLONY) as 'YEAR_DEV',
    a.ID
FROM ECOLI_DATA a
JOIN (
    SELECT MAX(SIZE_OF_COLONY) AS 'SIZE', YEAR(DIFFERENTIATION_DATE) AS 'YEAR'
    FROM ECOLI_DATA 
    GROUP BY YEAR
) m
ON m.YEAR = YEAR(a.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV
