-- 코드를 작성해주세요
SELECT SUM(SCORE) as 'SCORE', hre.EMP_NO, hre.EMP_NAME, hre.POSITION, hre.EMAIL
FROM HR_EMPLOYEES hre
JOIN HR_GRADE hrg ON hre.EMP_NO = hrg.EMP_NO
GROUP BY hre.EMP_NO
ORDER BY SCORE DESC
LIMIT 1